<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel - Ticket Booking</title>
    <link rel="stylesheet" href="adminhome.css">
</head>
<body>

<div class="admin-container">
    <h2>Welcome Admin</h2>
    <br>
    <div class="options">
        <a href="delete.php"><button>DELETE/MODIFY MOVIE</button></a>
        <a href="addmovie.php"><button>ADD MOVIE</button></a>
        <a href="upcoming.php"><button>ADD UPCOMING MOVIES</button></a>
        <a href="offers.php"><button>ADD OFFERS</button></a>


        
    </div>
</div>

</body>
</html>
